# Generated by Django 6.1.1 on 2026-09-17 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('body_region', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['body_region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_status', models.CharField(choices=[('not_started', 'Have not started PT'), ('currently_in', 'Currently in PT'), ('completed', 'Completed PT'), ('planning', 'Planning to start PT')], default='not_started', max_length=20)),
                ('current_facility', models.CharField(blank=True, max_length=200)),
                ('had_surgery', models.BooleanField(default=False)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('pain_level', models.IntegerField(default=5)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.diagnosis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
