# Generated by Django 6.1.1 on 2026-09-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('acute', 'Acute / Initial'), ('subacute', 'Sub-Acute'), ('strengthening', 'Strengthening'), ('advanced', 'Advanced / Return to Sport'), ('maintenance', 'Maintenance')], max_length=20)),
                ('pain_level_min', models.IntegerField(default=1)),
                ('pain_level_max', models.IntegerField(default=10)),
                ('sets', models.CharField(default='3', max_length=20)),
                ('reps', models.CharField(default='10', max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='exercises/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.diagnosis')),
            ],
            options={
                'ordering': ['diagnosis', 'phase', 'difficulty'],
            },
        ),
    ]
