from django.core.management.base import BaseCommand
from exercises.models import Exercise
from accounts.models import Diagnosis


EXERCISES = {
    'acl-tear': [
        # Acute
        {'title': 'Quad Sets', 'description': 'Tighten your quadriceps by pressing the back of your knee into the floor. Hold for 5 seconds and release.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Straight Leg Raises', 'description': 'Lie on your back, tighten the quad on your injured leg, and lift the leg 12 inches off the ground. Hold 3 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Ankle Pumps', 'description': 'While lying down, pump your ankle up and down to promote blood circulation and reduce swelling.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20', 'difficulty': 'beginner'},
        {'title': 'Heel Slides', 'description': 'Lie on your back and slowly slide your heel toward your buttocks, bending the knee. Slide back to start.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        # Sub-Acute
        {'title': 'Mini Squats', 'description': 'Stand with feet shoulder-width apart. Bend knees to 45 degrees, keeping weight on heels. Return to standing.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Step-Ups (Low)', 'description': 'Step up onto a 4-6 inch step with your injured leg, then step down slowly. Focus on control.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Hamstring Curls (Standing)', 'description': 'Stand holding a chair for balance. Bend your knee bringing heel toward buttocks. Lower slowly.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Stationary Bike', 'description': 'Pedal on a stationary bike with low resistance. Focus on full range of motion in the knee.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '1', 'reps': '10-15 min', 'difficulty': 'beginner'},
        # Strengthening
        {'title': 'Wall Sits', 'description': 'Lean against a wall with knees bent at 60 degrees. Hold position for 30 seconds.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '30 sec hold', 'difficulty': 'intermediate'},
        {'title': 'Leg Press', 'description': 'Use a leg press machine with moderate weight. Push through your heels and control the descent.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Single-Leg Balance', 'description': 'Stand on your injured leg for 30 seconds. Progress to closing your eyes or standing on an unstable surface.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '30 sec hold', 'difficulty': 'intermediate'},
        {'title': 'Lateral Band Walks', 'description': 'Place a resistance band around your ankles. Take side steps while maintaining tension in the band.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '15 each way', 'difficulty': 'intermediate'},
        # Advanced
        {'title': 'Single-Leg Squats', 'description': 'Stand on one leg and perform a squat to 60 degrees. Use a chair for balance if needed.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '8', 'difficulty': 'advanced'},
        {'title': 'Box Jumps', 'description': 'Jump onto a low box (12-18 inches) and land softly with both feet. Step down and repeat.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '8', 'difficulty': 'advanced'},
        {'title': 'Agility Ladder Drills', 'description': 'Perform various footwork patterns through an agility ladder. Focus on quick, controlled movements.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '5 passes', 'difficulty': 'advanced'},
        {'title': 'Lateral Bounding', 'description': 'Jump laterally from one foot to the other, covering 2-3 feet per bound. Land softly on each foot.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '10', 'difficulty': 'advanced'},
        # Maintenance
        {'title': 'Full Squats', 'description': 'Perform full-depth squats with proper form. Add weight as tolerated.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '4', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Lunges', 'description': 'Perform walking lunges with control. Keep your front knee aligned over your ankle.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12 each leg', 'difficulty': 'intermediate'},
        {'title': 'Deadlifts', 'description': 'Perform Romanian deadlifts with dumbbells or barbell. Focus on hamstring engagement and hip hinge.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '10', 'difficulty': 'advanced'},
        {'title': 'Sport-Specific Drills', 'description': 'Perform cutting, pivoting, and sport-specific movements at game speed. Monitor for any pain or instability.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '5 min', 'difficulty': 'advanced'},
    ],
    'rotator-cuff': [
        {'title': 'Pendulum Swings', 'description': 'Lean forward and let your arm hang. Gently swing it in small circles to promote mobility.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20 circles', 'difficulty': 'beginner'},
        {'title': 'Passive Shoulder Flexion', 'description': 'Use your good arm to lift the injured arm overhead while lying down. Hold for 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Isometric External Rotation', 'description': 'Stand next to a wall with elbow at 90 degrees. Push the back of your hand into the wall. Hold 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Scapular Squeezes', 'description': 'Sit or stand with good posture. Squeeze shoulder blades together and hold for 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'External Rotation with Band', 'description': 'Hold a resistance band with elbow at your side bent to 90 degrees. Rotate your forearm outward.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Internal Rotation with Band', 'description': 'Hold a resistance band with elbow at your side bent to 90 degrees. Rotate your forearm across your body.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Side-Lying External Rotation', 'description': 'Lie on your uninjured side. Hold a light weight with your top arm and rotate it upward, elbow at side.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Wall Slides', 'description': 'Stand facing a wall. Slide your forearms up the wall, then back down. Maintain contact with the wall.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Prone Y Raises', 'description': 'Lie face-down with arms at sides. Raise arms overhead in a Y position with thumbs pointing up.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Prone T Raises', 'description': 'Lie face-down with arms at sides. Raise arms out to the side in a T position with thumbs up.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Shoulder Press (Light)', 'description': 'Press light dumbbells overhead from shoulder height. Keep core engaged and avoid arching back.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Rows with Band', 'description': 'Anchor a band at chest height. Pull toward your body, squeezing shoulder blades together.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Push-Ups (Wall to Floor)', 'description': 'Start with wall push-ups and progress to incline, then floor push-ups as strength increases.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'advanced'},
        {'title': 'Overhead Carries', 'description': 'Hold a weight overhead with a straight arm. Walk 30-50 feet maintaining shoulder stability.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '40 ft', 'difficulty': 'advanced'},
        {'title': 'Plank to Push-Up', 'description': 'Start in a forearm plank. Push up to a straight-arm plank one arm at a time. Alternate leading arms.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '8', 'difficulty': 'advanced'},
        {'title': 'Face Pulls', 'description': 'Use a cable or band at face height. Pull toward your face, externally rotating at the end.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '15', 'difficulty': 'intermediate'},
        {'title': 'Dumbbell Shoulder Complex', 'description': 'Perform front raise, lateral raise, and reverse fly as a complex with light dumbbells.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '8 each', 'difficulty': 'intermediate'},
        {'title': 'Turkish Get-Up', 'description': 'Perform a full Turkish get-up with a kettlebell or dumbbell. Focus on shoulder stability throughout.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '2', 'reps': '3 each side', 'difficulty': 'advanced'},
    ],
    'lower-back-pain': [
        {'title': 'Pelvic Tilts', 'description': 'Lie on your back with knees bent. Flatten your back against the floor by tightening your abs. Hold 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Knee-to-Chest Stretch', 'description': 'Lie on your back. Pull one knee to your chest and hold for 20 seconds. Repeat on the other side.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '20 sec each', 'difficulty': 'beginner'},
        {'title': 'Cat-Cow Stretch', 'description': 'On hands and knees, alternate between arching and rounding your back. Move slowly and gently.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Supine Piriformis Stretch', 'description': 'Lie on your back. Cross one ankle over opposite knee and pull thigh toward chest. Hold 20 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '20 sec each', 'difficulty': 'beginner'},
        {'title': 'Bird-Dog', 'description': 'On hands and knees, extend opposite arm and leg simultaneously. Hold 5 seconds. Alternate sides.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10 each side', 'difficulty': 'beginner'},
        {'title': 'Bridges', 'description': 'Lie on your back with knees bent. Lift hips off the floor, squeezing glutes. Hold 5 seconds at top.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Partial Crunches', 'description': 'Lie on your back with knees bent. Tighten abs and raise shoulders off floor. Do not pull with your neck.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Seated Hamstring Stretch', 'description': 'Sit with one leg extended. Reach toward your toes while keeping your back straight. Hold 20 seconds.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '20 sec each', 'difficulty': 'beginner'},
        {'title': 'Dead Bug', 'description': 'Lie on your back with arms up and knees at 90 degrees. Lower opposite arm and leg while maintaining back position.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10 each side', 'difficulty': 'intermediate'},
        {'title': 'Side Plank', 'description': 'Lie on your side and lift your hips, supporting on forearm and feet. Hold for 20-30 seconds.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '20 sec each', 'difficulty': 'intermediate'},
        {'title': 'Superman', 'description': 'Lie face-down. Simultaneously lift arms, chest, and legs off the floor. Hold 3 seconds.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Pallof Press', 'description': 'Use a cable or band at chest height. Press outward and resist the rotation. Hold 3 seconds.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '10 each side', 'difficulty': 'intermediate'},
        {'title': 'Front Plank', 'description': 'Hold a forearm plank position with a straight line from head to heels. Engage core throughout.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '45 sec', 'difficulty': 'intermediate'},
        {'title': 'Kettlebell Swings', 'description': 'Perform hip-hinge kettlebell swings with proper form. Drive through the hips, not the lower back.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '15', 'difficulty': 'advanced'},
        {'title': 'Back Extensions', 'description': 'Using a back extension bench, hinge at the hips and extend back up to neutral. Do not hyperextend.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'McGill Big 3 Circuit', 'description': 'Perform curl-up, side plank, and bird-dog as a circuit. These are the gold standard for back stability.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': 'circuit', 'difficulty': 'intermediate'},
        {'title': 'Hip Hinge with Band', 'description': 'Loop a band around hips anchored behind you. Practice the hip hinge pattern against band resistance.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Goblet Squats', 'description': 'Hold a dumbbell at chest height. Squat with good form, keeping the back neutral.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
    ],
    'ankle-sprain': [
        {'title': 'Ankle Alphabet', 'description': 'Sit with your foot elevated. Use your big toe to trace the letters of the alphabet in the air.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '2', 'reps': 'A-Z', 'difficulty': 'beginner'},
        {'title': 'Towel Scrunches', 'description': 'Place a towel on the floor. Use your toes to scrunch it toward you, then push it away.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Ankle Circles', 'description': 'Sit with foot elevated. Slowly rotate your ankle in circles, 10 in each direction.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10 each way', 'difficulty': 'beginner'},
        {'title': 'Calf Raises (Seated)', 'description': 'Sit with feet flat on the floor. Raise your heels off the ground, then lower slowly.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Resistance Band Dorsiflexion', 'description': 'Loop a band around your foot and anchor it. Pull your toes toward your shin against the resistance.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Resistance Band Eversion', 'description': 'Loop a band around your foot anchored to the inside. Turn your foot outward against resistance.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Balance Board Training', 'description': 'Stand on a wobble board or BOSU ball. Maintain balance for 30 seconds. Progress as able.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '30 sec', 'difficulty': 'intermediate'},
        {'title': 'Standing Calf Raises', 'description': 'Stand on the edge of a step. Rise up on your toes, then lower below the step level.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '15', 'difficulty': 'intermediate'},
        {'title': 'Single-Leg Calf Raises', 'description': 'Perform calf raises on one leg. Use a wall for balance support if needed.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Lateral Hops', 'description': 'Hop side to side over a line. Land softly and maintain balance. Progress to single-leg hops.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '10 each way', 'difficulty': 'advanced'},
        {'title': 'Single-Leg Hop and Stick', 'description': 'Hop forward on one foot and stick the landing. Hold the landing for 3 seconds.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 2, 'sets': '3', 'reps': '8', 'difficulty': 'advanced'},
        {'title': 'Jump Rope', 'description': 'Jump rope for ankle strengthening and proprioception. Start with 30-second intervals.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '1 min', 'difficulty': 'intermediate'},
        {'title': 'Trail Walking', 'description': 'Walk on uneven terrain to challenge ankle proprioception and strength. Wear supportive shoes.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '15 min', 'difficulty': 'beginner'},
    ],
    'tennis-elbow': [
        {'title': 'Wrist Extensor Stretch', 'description': 'Extend your arm with palm down. Use other hand to gently press fingers toward you. Hold 20 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Wrist Flexor Stretch', 'description': 'Extend your arm with palm up. Use other hand to gently press fingers toward the floor. Hold 20 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Fist Clenches', 'description': 'Squeeze a soft ball or rolled-up towel. Hold for 5 seconds, then release. Builds grip strength gently.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Wrist Curls', 'description': 'Rest forearm on table with wrist hanging over edge, palm up. Curl a light weight up and lower slowly.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Reverse Wrist Curls', 'description': 'Rest forearm on table, palm down. Lift light weight by extending wrist upward. Lower slowly.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Pronation/Supination', 'description': 'Hold a hammer or weighted object. Slowly rotate forearm palm-up to palm-down and back.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Tyler Twist (Eccentric)', 'description': 'Use a FlexBar. Twist it with your affected wrist, then slowly release. Key eccentric exercise for tennis elbow.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Grip Strengthener', 'description': 'Use a hand grip strengthener. Squeeze and hold for 5 seconds. Increase resistance progressively.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Eccentric Wrist Extensions', 'description': 'Hold a dumbbell palm-down. Use other hand to lift into extension, then slowly lower with just the injured arm.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Resisted Wrist Pronation', 'description': 'Use a resistance band or weight for resisted forearm pronation. Control the movement in both directions.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Forearm Plank', 'description': 'Hold a forearm plank to strengthen the entire kinetic chain. Keep wrists in neutral position.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '30 sec', 'difficulty': 'intermediate'},
        {'title': 'Maintenance Stretching Routine', 'description': 'Perform wrist extensor and flexor stretches daily. Use warm-up before any gripping activities.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '2', 'reps': '30 sec each', 'difficulty': 'beginner'},
    ],
    'hip-replacement': [
        {'title': 'Ankle Pumps (Post-Op)', 'description': 'Pump your ankles up and down frequently to promote circulation and prevent blood clots.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20', 'difficulty': 'beginner'},
        {'title': 'Quad Sets (Supine)', 'description': 'Lie on your back. Tighten your thigh muscle, pressing your knee flat. Hold 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Gluteal Squeezes', 'description': 'Squeeze your buttock muscles together as tightly as possible. Hold 5 seconds and release.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Heel Slides (Hip)', 'description': 'Slide your heel toward your buttock, bending the hip and knee. Do not exceed 90 degrees of hip flexion.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Standing Hip Abduction', 'description': 'Hold onto a counter. Slowly lift your operated leg out to the side. Keep toes forward.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Standing Hip Extension', 'description': 'Hold onto a counter. Slowly move your operated leg backward. Keep your back straight.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Marching in Place', 'description': 'Stand and lift your knees alternately as if marching. Do not lift knee above hip level.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '20', 'difficulty': 'beginner'},
        {'title': 'Sit-to-Stand', 'description': 'From a high chair, stand up using both legs. Sit back down slowly. Avoid low seats initially.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Hip Bridges', 'description': 'Lie on your back with knees bent. Lift hips and squeeze glutes at top. Lower slowly.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Clamshells', 'description': 'Lie on your side with knees bent. Lift top knee while keeping feet together. Strengthens hip abductors.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Step-Ups', 'description': 'Step up onto a 4-6 inch step leading with your operated leg. Step down slowly.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Partial Squats', 'description': 'Stand with feet shoulder-width apart. Bend knees to 45 degrees, then stand back up.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Stationary Bike (Hip)', 'description': 'Ride a stationary bike with gradually increasing resistance. Keep good posture.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '15-20 min', 'difficulty': 'intermediate'},
        {'title': 'Walking Program', 'description': 'Walk on flat surfaces, gradually increasing distance. Use proper gait pattern with no limp.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '20-30 min', 'difficulty': 'beginner'},
        {'title': 'Swimming / Water Walking', 'description': 'Swim or walk in a pool for low-impact conditioning once your incision is fully healed.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '20-30 min', 'difficulty': 'beginner'},
    ],
    'meniscus-tear': [
        {'title': 'Straight Leg Raises (Meniscus)', 'description': 'Lie on your back. Tighten your quad and lift the leg 12 inches. Hold 3 seconds. Builds quad without stressing knee.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Prone Knee Flexion', 'description': 'Lie face-down. Slowly bend your knee as far as comfortable. Hold briefly, then lower.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Standing Hamstring Curl', 'description': 'Stand holding a chair. Bend your knee, bringing heel toward buttocks. Lower slowly.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Calf Raises (Meniscus)', 'description': 'Stand on both feet. Rise up onto toes, hold 2 seconds, then lower. Supports overall leg strength.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Leg Extensions (Limited Range)', 'description': 'Sit on a chair. Extend your leg from 90 to 45 degrees only. Avoid full extension if painful.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Wall Squats (Meniscus)', 'description': 'Lean against wall with ball behind back. Squat to 45-60 degrees only. Hold 5 seconds.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Step-Downs', 'description': 'Stand on a step. Slowly lower your uninjured foot toward the floor, then push back up. Controls descent.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Dynamic Balance Drills', 'description': 'Stand on one leg while performing arm movements or catching a ball. Challenges knee stability.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '30 sec', 'difficulty': 'advanced'},
        {'title': 'Cycling for Endurance', 'description': 'Ride a stationary bike at moderate resistance. Great for knee range of motion without impact.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '20 min', 'difficulty': 'beginner'},
        {'title': 'Elliptical Training', 'description': 'Use an elliptical machine for low-impact cardio that maintains knee strength and mobility.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '20 min', 'difficulty': 'beginner'},
    ],
    'frozen-shoulder': [
        {'title': 'Pendulum Swings (Shoulder)', 'description': 'Lean over and let your arm hang. Gently swing in small circles. Increase circle size as tolerated.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20 circles', 'difficulty': 'beginner'},
        {'title': 'Finger Wall Walk (Forward)', 'description': 'Face a wall and walk your fingers up as high as possible. Hold at top for 10 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '5', 'difficulty': 'beginner'},
        {'title': 'Towel Stretch (Behind Back)', 'description': 'Hold a towel behind your back with both hands. Use the top hand to gently pull the bottom hand up.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Cross-Body Stretch', 'description': 'Use your good arm to pull the affected arm across your body. Hold for 20 seconds.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Passive External Rotation', 'description': 'Hold a stick with both hands at waist level. Push the affected arm outward using the stick and good arm.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Sleeper Stretch', 'description': 'Lie on affected side with elbow at 90 degrees. Use the other hand to push the forearm toward the bed.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Active Assisted Flexion', 'description': 'Use a cane or dowel to push the affected arm overhead with assistance from the good arm.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Band Pull-Aparts', 'description': 'Hold a light resistance band in front at chest height. Pull it apart horizontally. Squeeze shoulder blades.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Wall Push-Ups (Frozen Shoulder)', 'description': 'Stand arm-length from wall. Perform push-ups against the wall to build shoulder strength gently.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Full Range Stretching Routine', 'description': 'Combine all shoulder stretches into a daily routine. Maintain gains and prevent re-stiffening.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '2', 'reps': '5 min routine', 'difficulty': 'beginner'},
    ],
    'plantar-fasciitis': [
        {'title': 'Towel Stretch (Foot)', 'description': 'Sit with leg straight. Loop a towel around the ball of your foot and gently pull toward you. Hold 20 sec.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Frozen Water Bottle Roll', 'description': 'Roll a frozen water bottle under the arch of your foot for massage and pain relief.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 8, 'sets': '3', 'reps': '2 min', 'difficulty': 'beginner'},
        {'title': 'Toe Curls with Towel', 'description': 'Place a towel on the floor. Use your toes to grip and scrunch the towel toward you.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '15', 'difficulty': 'beginner'},
        {'title': 'Calf Stretch (Wall)', 'description': 'Stand facing a wall. Step one foot back and press heel into floor. Lean forward until you feel stretch in calf.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '30 sec each', 'difficulty': 'beginner'},
        {'title': 'Marble Pick-Ups', 'description': 'Place marbles on the floor. Use your toes to pick them up one at a time and place in a cup.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '2', 'reps': '20 marbles', 'difficulty': 'beginner'},
        {'title': 'Eccentric Calf Drops', 'description': 'Stand on a step with balls of feet on the edge. Rise up, then slowly lower heels below step level.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Arch Strengthening', 'description': 'Stand with feet flat. Try to lift your arch without curling your toes (short foot exercise). Hold 5 sec.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '10', 'difficulty': 'intermediate'},
        {'title': 'Single-Leg Balance (Foot)', 'description': 'Stand on one foot for 30 seconds. Challenges foot intrinsic muscles and ankle stability.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '30 sec', 'difficulty': 'intermediate'},
        {'title': 'Walking on Varied Surfaces', 'description': 'Walk on grass, sand, and uneven terrain to strengthen foot muscles and improve proprioception.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '1', 'reps': '10-15 min', 'difficulty': 'intermediate'},
        {'title': 'Daily Stretching Maintenance', 'description': 'Perform calf and plantar fascia stretches first thing in the morning and after prolonged sitting.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '2', 'reps': '5 min', 'difficulty': 'beginner'},
    ],
    'carpal-tunnel': [
        {'title': 'Wrist Flexor Stretch (CTS)', 'description': 'Extend your arm with palm up. Gently pull fingers down and back with the other hand. Hold 20 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '20 sec', 'difficulty': 'beginner'},
        {'title': 'Nerve Gliding Exercise', 'description': 'Start with fist. Extend fingers straight, then bend wrist back, extend thumb, then turn palm up. Hold each 5 sec.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 7, 'sets': '3', 'reps': '5 cycles', 'difficulty': 'beginner'},
        {'title': 'Tendon Gliding Exercise', 'description': 'Move through positions: straight fingers, hook fist, full fist, tabletop, straight fist. Hold each 5 seconds.', 'phase': 'acute', 'pain_level_min': 1, 'pain_level_max': 6, 'sets': '3', 'reps': '5 cycles', 'difficulty': 'beginner'},
        {'title': 'Wrist Circles', 'description': 'Gently rotate your wrists in circles, 10 in each direction. Keep movements slow and controlled.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10 each way', 'difficulty': 'beginner'},
        {'title': 'Finger Spreads', 'description': 'Spread all fingers wide apart, hold 5 seconds, then close. Repeat to improve finger mobility.', 'phase': 'subacute', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '3', 'reps': '10', 'difficulty': 'beginner'},
        {'title': 'Grip Strengthening (CTS)', 'description': 'Squeeze a stress ball gently. Hold 3 seconds, release. Builds grip without aggravating symptoms.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Rubber Band Extensions', 'description': 'Place a rubber band around all five fingers. Open your hand against the resistance. Builds extensor strength.', 'phase': 'strengthening', 'pain_level_min': 1, 'pain_level_max': 4, 'sets': '3', 'reps': '12', 'difficulty': 'beginner'},
        {'title': 'Wrist Curls (Light, CTS)', 'description': 'Rest forearm on table. Curl a 1-2 lb weight with palm up. Then repeat palm down. Strengthens forearm.', 'phase': 'advanced', 'pain_level_min': 1, 'pain_level_max': 3, 'sets': '3', 'reps': '12', 'difficulty': 'intermediate'},
        {'title': 'Ergonomic Awareness Routine', 'description': 'Practice neutral wrist positioning during daily activities. Take breaks every 30 minutes for stretching.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '1', 'reps': 'ongoing', 'difficulty': 'beginner'},
        {'title': 'Daily Nerve & Tendon Glides', 'description': 'Perform nerve and tendon gliding exercises daily to maintain mobility and prevent symptom recurrence.', 'phase': 'maintenance', 'pain_level_min': 1, 'pain_level_max': 5, 'sets': '2', 'reps': '5 cycles', 'difficulty': 'beginner'},
    ],
}


class Command(BaseCommand):
    help = 'Seed the database with exercises for all diagnoses'

    def handle(self, *args, **options):
        created = 0
        for slug, exercises in EXERCISES.items():
            try:
                diagnosis = Diagnosis.objects.get(slug=slug)
            except Diagnosis.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'Diagnosis "{slug}" not found — skipping'))
                continue

            for ex_data in exercises:
                _, was_created = Exercise.objects.get_or_create(
                    title=ex_data['title'],
                    diagnosis=diagnosis,
                    defaults=ex_data,
                )
                if was_created:
                    created += 1

        total = sum(len(v) for v in EXERCISES.values())
        self.stdout.write(self.style.SUCCESS(f'Seeded {created} exercises ({total - created} already existed)'))
