from django.core.management.base import BaseCommand
from faq.models import FAQ
from accounts.models import Diagnosis


FAQS = [
    # General (no specific diagnosis)
    {'question': 'How long does physical therapy typically last?', 'answer': 'The duration of PT varies depending on your condition, severity, and goals. Most patients attend PT for 6-12 weeks, with sessions 2-3 times per week. Some conditions may require longer treatment. Your therapist will create a personalized plan and adjust as you progress.', 'diagnosis_slug': None, 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': True},
    {'question': 'Should I exercise if I feel pain?', 'answer': 'Mild discomfort during exercises is normal and expected, but sharp or worsening pain is a signal to stop. A general guideline is the "2-hour rule" — if your pain is worse 2 hours after exercising than before, you may have done too much. Always communicate your pain levels with your therapist.', 'diagnosis_slug': None, 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': True},
    {'question': 'What should I bring to my first PT appointment?', 'answer': 'Bring your insurance card, a referral from your doctor (if required), comfortable clothing that allows easy movement, any imaging results (MRI, X-ray), and a list of medications you are taking. Arrive 15 minutes early to complete paperwork.', 'diagnosis_slug': None, 'answered_by': 'Dr. Lisa Park, DPT', 'featured': True},
    {'question': 'Can I do PT exercises at home?', 'answer': 'Yes! Home exercises are a critical part of your recovery. Your therapist will give you a home exercise program (HEP) tailored to your condition. Consistency with home exercises often makes the biggest difference in recovery outcomes.', 'diagnosis_slug': None, 'answered_by': 'Dr. James Rodriguez, DPT', 'featured': True},
    # ACL
    {'question': 'When can I return to sports after ACL reconstruction?', 'answer': 'Return to sport after ACL reconstruction typically occurs at 9-12 months post-surgery, though this varies by individual. Your surgeon and PT will evaluate you using functional tests such as hop tests, strength measurements, and movement quality before clearing you for full sports participation.', 'diagnosis_slug': 'acl-tear', 'answered_by': 'Dr. Michael Torres, MD, Orthopedic Surgeon', 'featured': False},
    {'question': 'Is it normal for my knee to swell after ACL exercises?', 'answer': 'Some mild swelling after exercise is normal in the early stages of ACL rehabilitation. Apply ice for 15-20 minutes after your exercises. If swelling is significant, persistent, or accompanied by increased pain, contact your physical therapist or surgeon.', 'diagnosis_slug': 'acl-tear', 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': False},
    {'question': 'Do I need a brace after ACL surgery?', 'answer': 'Your surgeon will determine if a brace is necessary. Many protocols use a brace for the first 4-6 weeks to protect the graft. Some newer protocols emphasize early mobility without a brace. Follow your surgeon\'s specific instructions regarding brace use.', 'diagnosis_slug': 'acl-tear', 'answered_by': 'Dr. Michael Torres, MD, Orthopedic Surgeon', 'featured': False},
    {'question': 'How do I know if my ACL graft is failing?', 'answer': 'Signs of graft failure include a feeling of instability or the knee "giving way," persistent swelling, inability to bear weight, or a loss of range of motion that was previously restored. If you experience any of these, contact your surgeon immediately for evaluation.', 'diagnosis_slug': 'acl-tear', 'answered_by': 'Dr. Amanda Foster, MD', 'featured': False},
    # Rotator Cuff
    {'question': 'How do I sleep comfortably with a rotator cuff injury?', 'answer': 'Sleep in a reclined position or on your back with a pillow under the injured arm. Avoid sleeping on the affected side. A recliner chair can be helpful in the early stages. Place a pillow between your arm and body for support. Over-the-counter pain medication before bed can help.', 'diagnosis_slug': 'rotator-cuff', 'answered_by': 'Dr. Lisa Park, DPT', 'featured': False},
    {'question': 'Can a rotator cuff tear heal without surgery?', 'answer': 'Many partial rotator cuff tears and some full-thickness tears can be managed conservatively with PT. Success depends on the tear size, location, patient age, activity level, and functional demands. Your orthopedist can help determine the best approach for your specific case.', 'diagnosis_slug': 'rotator-cuff', 'answered_by': 'Dr. Robert Kim, MD, Sports Medicine', 'featured': False},
    {'question': 'Why is my shoulder so stiff after rotator cuff surgery?', 'answer': 'Stiffness after rotator cuff surgery is very common, especially in the first 6-12 weeks. The surgical repair needs to be protected, which limits movement. Your PT will gradually introduce range-of-motion exercises according to your surgeon\'s protocol to restore mobility while protecting the repair.', 'diagnosis_slug': 'rotator-cuff', 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': False},
    {'question': 'How long should I wear my sling after rotator cuff surgery?', 'answer': 'Most surgeons recommend wearing a sling for 4-6 weeks after rotator cuff repair, though this varies based on the size of the tear repaired and the surgical technique used. Your surgeon will provide specific guidelines. The sling protects the repair during the critical early healing phase.', 'diagnosis_slug': 'rotator-cuff', 'answered_by': 'Dr. Robert Kim, MD, Sports Medicine', 'featured': False},
    # Lower Back
    {'question': 'Should I use heat or ice for my lower back pain?', 'answer': 'For acute back pain (first 48-72 hours), ice is generally recommended to reduce inflammation — apply for 15-20 minutes at a time. For chronic or muscle-related back pain, heat is often more beneficial as it increases blood flow and relaxes muscles. Some people benefit from alternating between both.', 'diagnosis_slug': 'lower-back-pain', 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': False},
    {'question': 'Is bed rest good for lower back pain?', 'answer': 'Extended bed rest is not recommended for most cases of lower back pain. Research shows that staying active (within your pain tolerance) leads to faster recovery. Brief rest periods (1-2 days maximum) may help with severe acute pain, but prolonged inactivity can actually worsen symptoms and delay healing.', 'diagnosis_slug': 'lower-back-pain', 'answered_by': 'Dr. James Rodriguez, DPT', 'featured': False},
    {'question': 'When should I see a doctor for back pain?', 'answer': 'Seek immediate medical attention if your back pain is accompanied by numbness in the groin area, loss of bladder or bowel control, severe weakness in your legs, or follows a significant trauma. See a doctor if pain persists beyond 2-3 weeks, wakes you from sleep, or is accompanied by unexplained weight loss.', 'diagnosis_slug': 'lower-back-pain', 'answered_by': 'Dr. Amanda Foster, MD', 'featured': False},
    {'question': 'Can core exercises really help my back pain?', 'answer': 'Yes. Strong core muscles (including abdominals, back extensors, and hip muscles) provide support for your spine. Research consistently shows that core stability exercises are one of the most effective treatments for chronic lower back pain. The key is performing them with proper form — quality over quantity.', 'diagnosis_slug': 'lower-back-pain', 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': False},
    # Ankle Sprain
    {'question': 'How do I know if my ankle is sprained or broken?', 'answer': 'It can be difficult to tell without imaging. Signs that suggest a fracture include inability to bear weight, severe bruising, deformity, point tenderness over the bone (not the ligament), and hearing a crack at the time of injury. If in doubt, seek medical evaluation for an X-ray.', 'diagnosis_slug': 'ankle-sprain', 'answered_by': 'Dr. Amanda Foster, MD', 'featured': False},
    {'question': 'Should I wrap my sprained ankle?', 'answer': 'Yes, compression with an elastic bandage can help reduce swelling in the first few days. Wrap firmly but not so tight that it causes numbness or tingling. Remove the wrap when sleeping. As swelling decreases, you can transition to an ankle brace for support during activity.', 'diagnosis_slug': 'ankle-sprain', 'answered_by': 'Dr. Lisa Park, DPT', 'featured': False},
    {'question': 'How long before I can walk normally after an ankle sprain?', 'answer': 'Grade 1 sprains (mild) typically allow normal walking within 1-2 weeks. Grade 2 sprains (moderate) may take 3-6 weeks. Grade 3 sprains (severe) can take 6-12 weeks or longer. Your PT will guide you through a progressive weight-bearing program to safely return to normal walking.', 'diagnosis_slug': 'ankle-sprain', 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': False},
    # Hip Replacement
    {'question': 'What movements should I avoid after hip replacement?', 'answer': 'With posterior approach surgery, avoid bending the hip past 90 degrees, crossing your legs, and internally rotating the hip for at least 6-12 weeks. With anterior approach, restrictions are usually fewer. Your surgeon will provide specific precautions based on your surgical approach.', 'diagnosis_slug': 'hip-replacement', 'answered_by': 'Dr. Michael Torres, MD, Orthopedic Surgeon', 'featured': False},
    {'question': 'How long does a hip replacement last?', 'answer': 'Modern hip replacements typically last 15-25 years or more, depending on activity level, body weight, and the type of implant used. Advances in materials and surgical techniques continue to improve implant longevity. Regular follow-up with your surgeon is important for monitoring.', 'diagnosis_slug': 'hip-replacement', 'answered_by': 'Dr. Robert Kim, MD, Sports Medicine', 'featured': False},
    {'question': 'When can I drive after hip replacement?', 'answer': 'For right hip replacement, most surgeons recommend waiting at least 4-6 weeks before driving. For left hip replacement with an automatic transmission, you may be cleared sooner (2-4 weeks). You must be off narcotic pain medications and able to react quickly to brake. Ask your surgeon for clearance.', 'diagnosis_slug': 'hip-replacement', 'answered_by': 'Dr. Michael Torres, MD, Orthopedic Surgeon', 'featured': False},
    # Meniscus
    {'question': 'Can a meniscus tear heal on its own?', 'answer': 'Some meniscus tears can heal without surgery, particularly small tears in the outer third of the meniscus (the "red zone") which has a blood supply. Larger tears, tears in the inner portion, and tears causing mechanical symptoms (locking, catching) often require surgical intervention.', 'diagnosis_slug': 'meniscus-tear', 'answered_by': 'Dr. Robert Kim, MD, Sports Medicine', 'featured': False},
    {'question': 'What is the difference between a meniscus repair and meniscectomy?', 'answer': 'A meniscus repair stitches the torn tissue back together, preserving the meniscus. A meniscectomy removes the damaged portion. Repair is preferred when possible as it preserves the meniscus\'s cushioning function, but it requires a longer recovery (4-6 months vs. 4-6 weeks for meniscectomy).', 'diagnosis_slug': 'meniscus-tear', 'answered_by': 'Dr. Michael Torres, MD, Orthopedic Surgeon', 'featured': False},
    # Frozen Shoulder
    {'question': 'How long does frozen shoulder last?', 'answer': 'Frozen shoulder typically progresses through three stages: freezing (2-9 months of increasing pain and stiffness), frozen (4-12 months of less pain but continued stiffness), and thawing (5-24 months of gradual improvement). The total course can be 1-3 years, though PT can significantly shorten recovery.', 'diagnosis_slug': 'frozen-shoulder', 'answered_by': 'Dr. Lisa Park, DPT', 'featured': False},
    {'question': 'Should I push through the pain with frozen shoulder stretches?', 'answer': 'Gentle stretching within your tolerance is important, but aggressive forcing through severe pain can worsen inflammation and slow recovery. Stretch to the point of mild discomfort, hold, and breathe. Over time, your range will improve. Working with a PT ensures you stretch appropriately.', 'diagnosis_slug': 'frozen-shoulder', 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': False},
    # Plantar Fasciitis
    {'question': 'Why does my heel hurt most in the morning?', 'answer': 'During sleep, your foot relaxes into a pointed position, allowing the plantar fascia to shorten. When you take your first steps, the fascia is suddenly stretched, causing that sharp heel pain. Night splints that keep the foot at 90 degrees and gentle stretching before getting up can help.', 'diagnosis_slug': 'plantar-fasciitis', 'answered_by': 'Dr. James Rodriguez, DPT', 'featured': False},
    {'question': 'What shoes are best for plantar fasciitis?', 'answer': 'Look for shoes with good arch support, cushioned soles, and a slightly elevated heel. Avoid flat shoes, flip-flops, and going barefoot. Brands like Brooks, New Balance, and ASICS often have models well-suited for plantar fasciitis. Custom or over-the-counter orthotics can also help significantly.', 'diagnosis_slug': 'plantar-fasciitis', 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': False},
    # Carpal Tunnel
    {'question': 'Should I wear a wrist splint for carpal tunnel?', 'answer': 'Yes, wearing a wrist splint at night is one of the first-line treatments for carpal tunnel syndrome. The splint keeps your wrist in a neutral position, reducing pressure on the median nerve. Some people also benefit from wearing a splint during aggravating activities. Your doctor can recommend the right type.', 'diagnosis_slug': 'carpal-tunnel', 'answered_by': 'Dr. Amanda Foster, MD', 'featured': False},
    {'question': 'Can carpal tunnel syndrome go away on its own?', 'answer': 'Mild carpal tunnel symptoms may improve with lifestyle modifications like ergonomic changes, activity modification, and splinting. However, without treatment, symptoms typically worsen over time. If you have persistent numbness, weakness, or dropping objects, see a healthcare provider for evaluation and treatment options.', 'diagnosis_slug': 'carpal-tunnel', 'answered_by': 'Dr. Lisa Park, DPT', 'featured': False},
    # Tennis Elbow
    {'question': 'How long does tennis elbow take to heal?', 'answer': 'Tennis elbow typically takes 6-12 months to fully resolve, though many people see significant improvement within 6-8 weeks with proper treatment including rest, ice, PT exercises, and a counterforce brace. The key is addressing the root cause — often overuse or improper technique — to prevent recurrence.', 'diagnosis_slug': 'tennis-elbow', 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': False},
    {'question': 'Should I use a brace for tennis elbow?', 'answer': 'A counterforce brace (worn just below the elbow) can help reduce strain on the tendon during activities. It works by dispersing the force away from the injured area. Use it during aggravating activities but not constantly. Combine with stretching, strengthening exercises, and activity modification for best results.', 'diagnosis_slug': 'tennis-elbow', 'answered_by': 'Dr. James Rodriguez, DPT', 'featured': False},
    # General additional
    {'question': 'Does insurance cover physical therapy?', 'answer': 'Most health insurance plans cover physical therapy, though the extent of coverage varies. Some plans require a referral from your primary care doctor, while others allow direct access. Check your plan for details on copays, deductibles, and any visit limits. Our facility finder can help you find in-network PT clinics.', 'diagnosis_slug': None, 'answered_by': 'NOVA PT Team', 'featured': True},
    {'question': 'What is the difference between a physical therapist and a chiropractor?', 'answer': 'Physical therapists focus on restoring movement and function through exercise, manual therapy, and education. They treat a wide range of musculoskeletal conditions. Chiropractors primarily focus on spinal alignment through adjustments. Both can be effective for certain conditions. A PT will create an active rehabilitation program that empowers you to manage your condition independently.', 'diagnosis_slug': None, 'answered_by': 'Dr. Sarah Chen, DPT', 'featured': False},
    {'question': 'How often should I do my home exercises?', 'answer': 'Most home exercise programs should be done 1-2 times daily, unless your PT specifies otherwise. Consistency is more important than intensity — doing your exercises every day for 15-20 minutes is better than one long session once a week. Always follow your specific PT\'s recommendations.', 'diagnosis_slug': None, 'answered_by': 'Dr. Marcus Williams, DPT', 'featured': False},
    {'question': 'Can telehealth PT be as effective as in-person visits?', 'answer': 'Research shows that telehealth PT can be very effective for many conditions, particularly for exercise instruction, education, and monitoring progress. It is especially useful for follow-up visits, home exercise program adjustments, and patients with transportation barriers. Some hands-on techniques still require in-person visits.', 'diagnosis_slug': None, 'answered_by': 'Dr. Lisa Park, DPT', 'featured': False},
]


class Command(BaseCommand):
    help = 'Seed the database with FAQs'

    def handle(self, *args, **options):
        created = 0
        for faq_data in FAQS:
            diagnosis = None
            slug = faq_data.pop('diagnosis_slug')
            if slug:
                try:
                    diagnosis = Diagnosis.objects.get(slug=slug)
                except Diagnosis.DoesNotExist:
                    self.stdout.write(self.style.WARNING(f'Diagnosis "{slug}" not found — skipping FAQ'))
                    continue

            _, was_created = FAQ.objects.get_or_create(
                question=faq_data['question'],
                defaults={**faq_data, 'diagnosis': diagnosis},
            )
            if was_created:
                created += 1

        self.stdout.write(self.style.SUCCESS(f'Seeded {created} FAQs ({len(FAQS) - created} already existed)'))
